export const FeatureFlags = {
	DEMO_FEATURE_FLAG: 'DEMO_FEATURE_FLAG',
	CHORE_TASK_TRACKER_ENABLED: 'CHORE_TASK_TRACKER_ENABLED',
	ACTIVITY_PICKER_ENABLED: 'ACTIVITY_PICKER_ENABLED',
	RETRO_ACHIEVEMENTS_ENABLED: 'RETRO_ACHIEVEMENTS_ENABLED',
	WEATHER_ENABLED: 'WEATHER_ENABLED',
	AUDIOBOOK_ENABLED: 'AUDIOBOOK_ENABLED',
	BOOKMARKS_ENABLED: 'BOOKMARKS_ENABLED'
};
